#!/usr/bin/env bash
# Regenerate patches/*.patch from the current tree.
#
# Each patch owns a disjoint set of upstream files (scripts/patch-files.txt), so
# series order never matters for applicability and a refresh is a plain
# `git diff <base_commit> HEAD -- <files>`. Run after editing an upstream file,
# then `scripts/sync-upstream.sh --dry-run` to prove the series replays.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

base_commit="$(sed -n 's/^base_commit = "\(.*\)"/\1/p' upstream-lock.toml)"
[[ -n "$base_commit" ]] || { echo "upstream-lock.toml has no base_commit" >&2; exit 1; }

declare -A seen
while IFS= read -r line; do
  entry="${line%%#*}"
  entry="$(echo "$entry" | xargs)"
  [[ -z "$entry" ]] && continue
  name="${entry%% *}"
  files="${entry#* }"
  for f in $files; do
    if [[ -n "${seen[$f]:-}" ]]; then
      echo "file $f listed twice (${seen[$f]} and $name); every upstream file belongs to exactly one patch" >&2
      exit 1
    fi
    seen[$f]="$name"
  done
  # shellcheck disable=SC2086
  git diff --no-color --no-ext-diff "$base_commit" -- $files > "patches/$name"
  if [[ ! -s "patches/$name" ]]; then
    echo "WARNING: patches/$name is empty (no change to: $files)" >&2
  fi
  echo "wrote patches/$name ($(grep -c '^diff --git' "patches/$name") files)"
done < scripts/patch-files.txt

# Every modified upstream file must be claimed by a patch.
unclaimed=0
while IFS= read -r f; do
  case "$f" in
    Cargo.lock) continue ;;  # regenerated by cargo during sync
  esac
  if [[ -z "${seen[$f]:-}" ]] && ! grep -qxF "$f" <(grep -v '^\s*#' scripts/overlay-paths.txt) \
     && ! grep -v '^\s*#' scripts/overlay-paths.txt | grep -v '^\s*$' | while read -r p; do [[ "$f" == "$p"/* ]] && echo hit; done | grep -q hit; then
    echo "UNCLAIMED upstream change: $f (add it to scripts/patch-files.txt)" >&2
    unclaimed=1
  fi
done < <(git diff --name-only "$base_commit" HEAD; git diff --name-only "$base_commit")
exit $unclaimed
