#!/usr/bin/env bash
# Regenerate every patches/*.patch from the diff between the locked upstream snapshot
# (upstream-lock.toml `git_sha`, present in this repository's history) and HEAD, split by the
# file groups declared in patches/groups.txt, and rewrite patches/series.
#
# The tree keeps upstream files in their patched state (quilt "pushed"); this script keeps
# patches/ in agreement with the tree. Run it after editing an upstream-owned file and commit the
# result together with the change. CI fails when patches/ and the tree disagree.
#
# For fixing a single patch during an upstream sync conflict use scripts/sync/refresh-patch.sh.
#
# patches/groups.txt format:   NNNN-name.patch<TAB>tags<TAB>path [path ...]
# patches/series format:       NNNN-name.patch  # tag [tag...]      (parsed by scripts/sync/lib.sh)
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
BASE="$(sed -n 's/^git_sha = "\(.*\)"/\1/p' upstream-lock.toml)"
[ -n "$BASE" ] || { echo "no git_sha in upstream-lock.toml" >&2; exit 1; }
git cat-file -e "${BASE}^{commit}" 2>/dev/null || { echo "upstream snapshot $BASE is not in this repository; fetch it (git fetch origin) first" >&2; exit 1; }

check_only=0
[ "${1:-}" = "--check" ] && check_only=1

series_tmp="$(mktemp)"; trap 'rm -f "$series_tmp"' EXIT
cat patches/series.header > "$series_tmp"
covered=()
declare -A generated
while IFS=$'\t' read -r patch tags paths; do
  [ -z "$patch" ] && continue
  case "$patch" in \#*) continue;; esac
  # Untracked new files under the group must show up in the diff (intent-to-add is enough).
  # shellcheck disable=SC2086
  git ls-files --others --exclude-standard -- $paths | while IFS= read -r f; do git add -N -- "$f"; done
  # Working tree vs the locked snapshot: equals HEAD in CI (clean tree), and lets you regenerate before committing.
  # shellcheck disable=SC2086
  content="$(git diff --no-color --no-ext-diff --binary "$BASE" -- $paths)"
  if [ -z "$content" ]; then
    echo "warning: $patch is empty (no diff for: $paths)" >&2
  fi
  generated["$patch"]=1
  if [ "$check_only" = 1 ]; then
    if [ "$(cat "patches/$patch" 2>/dev/null)" != "$content" ]; then
      echo "DRIFT: patches/$patch does not match the tree (run scripts/regenerate-patches.sh)" >&2
      drift=1
    fi
  else
    printf '%s\n' "$content" > "patches/$patch"
  fi
  printf '%s  # %s\n' "$patch" "$tags" >> "$series_tmp"
  # shellcheck disable=SC2206
  covered+=($paths)
done < patches/groups.txt

# Every changed upstream-owned path must belong to exactly one patch group.
mapfile -t overlay < <(sed -e 's/#.*//' -e 's/[[:space:]]*$//' -e 's:/*$::' -e '/^$/d' scripts/overlay-paths.txt)
is_overlay() {
  local p="$1" pat
  for pat in "${overlay[@]}"; do
    # shellcheck disable=SC2053
    if [[ "$p" == $pat || "$p" == $pat/* ]]; then return 0; fi
  done
  return 1
}
while IFS= read -r f; do
  [ -z "$f" ] && continue
  is_overlay "$f" && continue
  [ "$f" = "Cargo.lock" ] && continue   # regenerated by cargo, never patched
  hit=0
  for c in "${covered[@]}"; do
    case "$f" in "$c"|"$c"/*) hit=1;; esac
  done
  [ "$hit" = 1 ] || { echo "ERROR: upstream-owned file changed but not in any patch group: $f" >&2; exit 1; }
done < <(git diff --name-only "$BASE")

if [ "$check_only" = 1 ]; then
  if ! diff -q "$series_tmp" patches/series >/dev/null 2>&1; then
    echo "DRIFT: patches/series does not match patches/groups.txt" >&2; drift=1
  fi
  for f in patches/*.patch; do
    [ -n "${generated[$(basename "$f")]:-}" ] || { echo "DRIFT: stray patch file $f not in patches/groups.txt" >&2; drift=1; }
  done
  [ "${drift:-0}" = 0 ] && echo "patches/ agree with the tree" || exit 1
else
  cp "$series_tmp" patches/series && chmod 644 patches/series
  echo "regenerated $(grep -c '\.patch' patches/series) patches into patches/series (base $BASE)"
fi
