#!/usr/bin/env bash
# Regenerate patches/*.patch from the current tree.
#
# Each patch owns a disjoint set of upstream files (scripts/patch-files.txt), so
# series order never matters for applicability and a refresh is a plain
# `git diff <base_commit> HEAD -- <files>`. Run after editing an upstream file,
# then `scripts/sync-upstream.sh --dry-run` to prove the series replays.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

base_commit="$(sed -n 's/^base_commit = "\(.*\)"/\1/p' upstream-lock.toml)"
[[ -n "$base_commit" ]] || { echo "upstream-lock.toml has no base_commit" >&2; exit 1; }

declare -A owner
while IFS= read -r line; do
  entry="${line%%#*}"
  entry="$(echo "$entry" | xargs)"
  [[ -z "$entry" ]] && continue
  name="${entry%% *}"
  files="${entry#* }"
  for f in $files; do
    if [[ -n "${owner[$f]:-}" ]]; then
      echo "file $f listed twice (${owner[$f]} and $name); every upstream file belongs to exactly one patch" >&2
      exit 1
    fi
    owner[$f]="$name"
  done
  # shellcheck disable=SC2086
  git diff --no-color --no-ext-diff "$base_commit" HEAD -- $files > "patches/$name"
  if [[ ! -s "patches/$name" ]]; then
    echo "WARNING: patches/$name is empty (no change to: $files)" >&2
  fi
  echo "wrote patches/$name ($(grep -c '^diff --git' "patches/$name") files)"
done < scripts/patch-files.txt

# Every changed upstream-owned file must be claimed by exactly one patch.
is_overlay() {
  local f="$1" p
  while IFS= read -r p; do
    p="${p%%#*}"; p="$(echo "$p" | xargs)"
    [[ -z "$p" ]] && continue
    [[ "$f" == "$p" || "$f" == "$p"/* ]] && return 0
  done < scripts/overlay-paths.txt
  return 1
}
status=0
while IFS= read -r f; do
  [[ "$f" == "Cargo.lock" ]] && continue   # regenerated by cargo during sync
  is_overlay "$f" && continue
  if [[ -z "${owner[$f]:-}" ]]; then
    echo "UNCLAIMED upstream change: $f (add it to scripts/patch-files.txt)" >&2
    status=1
  fi
done < <(git diff --name-only "$base_commit" HEAD)
exit $status
